services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    restart: unless-stopped
    volumes:
      - .:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped
