services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ../qdrant_data:/qdrant/storage
